SELECT
 a.ID,
 IFNULL(b.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA AS a
LEFT JOIN (
 SELECT
  PARENT_ID,
  COUNT(PARENT_ID) AS CHILD_COUNT
 FROM ECOLI_DATA
 GROUP BY PARENT_ID) AS b
ON a.ID = b.PARENT_ID
ORDER BY a.ID ASC