WITH id AS (
 SELECT DISTINCT CAR_ID
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE START_DATE <= '2022-11-30'
   AND END_DATE >= '2022-11-01'
)

SELECT
 c.CAR_ID,
 c.CAR_TYPE,
 ROUND(c.DAILY_FEE * (1-d.DISCOUNT_RATE / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN (
 SELECT 
  CAR_TYPE,
  DURATION_TYPE,
  DISCOUNT_RATE
 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE DURATION_TYPE = '30일 이상'
 AND CAR_TYPE in ('세단','SUV')) AS d
ON c.CAR_TYPE = d.CAR_TYPE
WHERE c.CAR_TYPE in ('세단','SUV')
  AND c.CAR_ID NOT IN (SELECT CAR_ID FROM id)
  AND ROUND(c.DAILY_FEE * (1-d.DISCOUNT_RATE / 100) * 30) >= 500000
  AND ROUND(c.DAILY_FEE * (1-d.DISCOUNT_RATE / 100) * 30) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC