WITH id AS (
 SELECT
  MEMBER_ID
 FROM REST_REVIEW
 GROUP BY MEMBER_ID
 HAVING COUNT(*) = (
  SELECT MAX(CNT)
  FROM (
   SELECT COUNT(*) AS CNT
   FROM REST_REVIEW
   GROUP BY MEMBER_ID) AS c) 
)

SELECT
 m.MEMBER_NAME,
 r.REVIEW_TEXT,
 DATE_FORMAT(r.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS m
JOIN REST_REVIEW AS r
ON m.MEMBER_ID = r.MEMBER_ID
WHERE m.MEMBER_ID IN (SELECT MEMBER_ID FROM id)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC