SELECT
 p.PRODUCT_ID,
 p.PRODUCT_NAME,
 p.PRICE * o.AMOUNT AS TOTAL_AMOUNT
FROM FOOD_PRODUCT AS p
JOIN (
 SELECT 
  PRODUCT_ID,
  SUM(AMOUNT) AS AMOUNT
 FROM FOOD_ORDER
 WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
 GROUP BY PRODUCT_ID) AS o
ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY TOTAL_AMOUNT DESC, PRODUCT_ID ASC