SELECT 
 YEAR(s.SALES_DATE) AS YEAR,
 MONTH(s.SALES_DATE) AS MONTH,
 GENDER,
 COUNT(DISTINCT u.USER_ID) AS USERS
FROM USER_INFO AS u
JOIN ONLINE_SALE AS s
ON u.USER_ID = s.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER