WITH score AS (
 SELECT
  e.EMP_NO,
  e.EMP_NAME,
  AVG(g.SCORE) AS SCORE,
  AVG(e.SAL) AS SAL
 FROM HR_EMPLOYEES AS e
 JOIN HR_GRADE AS g
 ON e.EMP_NO = g.EMP_NO
 GROUP BY e.EMP_NO, e.EMP_NAME)
 
SELECT
 EMP_NO,
 EMP_NAME,
 (CASE WHEN SCORE >= 96 THEN 'S'
       WHEN SCORE >= 90 THEN 'A'
       WHEN SCORE >= 80 THEN 'B'
       ELSE 'C' END) AS GRADE,
 (CASE WHEN SCORE >= 96 THEN SAL*0.2
       WHEN SCORE >= 90 THEN SAL*0.15
       WHEN SCORE >= 80 THEN SAL*0.1
       ELSE SAL*0 END) AS BONUS
FROM score
ORDER BY EMP_NO ASC