SELECT
 b.BOOK_ID,
 a.AUTHOR_NAME,
 DATE_FORMAT(b.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR AS a
JOIN BOOK AS b
ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC