WITH j AS (SELECT 
 FLAVOR,
 SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR)

SELECT
 f.FLAVOR
FROM FIRST_HALF AS f
JOIN j
ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.TOTAL_ORDER) DESC
LIMIT 3