WITH RECURSIVE PARENT AS(
 SELECT 
  ID,
  PARENT_ID,
  1 AS GENERATION
 FROM ECOLI_DATA
 WHERE PARENT_ID IS NULL 

 UNION ALL

 SELECT
  e.ID,
  e.PARENT_ID,
  p.GENERATION+1
 FROM ECOLI_DATA AS e
 JOIN PARENT AS p
 ON e.PARENT_ID = p.ID
)
SELECT 
 SUM(b.CHILD_COUNT IS NULL) AS COUNT,
 a.GENERATION
FROM PARENT AS a
LEFT JOIN (
    SELECT
     PARENT_ID,
     COUNT(PARENT_ID) AS CHILD_COUNT
    FROM PARENT
    GROUP BY PARENT_ID) AS b
ON a.ID = b.PARENT_ID
GROUP BY a.GENERATION
ORDER BY a.GENERATION ASC