SELECT
 c.SALES_DATE,
 c.PRODUCT_ID,
 c.USER_ID,
 SUM(c.SALES_AMOUNT) AS SALES_AMOUNT
FROM (
 SELECT 
  DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
  PRODUCT_ID,
  USER_ID,
  SALES_AMOUNT
 FROM ONLINE_SALE
 WHERE SALES_DATE LIKE '2022-03%'

 UNION ALL

 SELECT 
  DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
  PRODUCT_ID,
  NULL AS USER_ID,
  SALES_AMOUNT
 FROM OFFLINE_SALE
 WHERE SALES_DATE LIKE '2022-03%') AS c
GROUP BY c.SALES_DATE, c.PRODUCT_ID, c.USER_ID
ORDER BY c.SALES_DATE, c.PRODUCT_ID, c.USER_ID