SELECT
 a.REST_ID,
 a.REST_NAME,
 a.FOOD_TYPE,
 a.FAVORITES,
 a.ADDRESS,
 b.SCORE
FROM REST_INFO AS a
JOIN (
 SELECT
  REST_ID,
  ROUND(AVG(REVIEW_SCORE),2) AS SCORE
 FROM REST_REVIEW
 GROUP BY REST_ID) AS b
ON a.REST_ID = b.REST_ID
WHERE a.ADDRESS LIKE '서울%'
ORDER BY b.SCORE DESC, a.FAVORITES DESC